package Repository;

import Domain.Film;

import java.util.*;

import javax.jdo.PersistenceManager;
import javax.jdo.Query;

@SuppressWarnings("unchecked")
public class FilmDAO {

	private FilmDAO() {}	
	
	/**
	 * Function to get All the films in an ArrayList
	 */
	public static List<Film> getAllFilms(){
	   
	   PersistenceManager pm = PMF.get().getPersistenceManager();
		
		Query q = pm.newQuery(Film.class);

		List<Film> results = null;

		try {
			results = (List<Film>) q.execute();
		} finally {
			q.closeAll();
		}
		return results;
	}
	
	/**
	 * This function returns a Film object with a certain name introduced by the USER
	 */
	public static List<Film> getFilmByTitle(String name){
	   name = name.toUpperCase();
	  PersistenceManager pm = PMF.get().getPersistenceManager();

	  Query q = pm.newQuery("SELECT FROM Domain.Film where :this.title.matches('"+name+".*')");

	  List<Film> results = null;

		try {
			results = (List<Film>) q.execute();  
		} finally {
			q.closeAll();
		}
		
	  return results;
   	}
	
	/**
	 * This function adds a film into the DB
	 */
    public static void addFilm(Film film) {
    	PersistenceManager pm = PMF.get().getPersistenceManager();
    	try {
    		pm.makePersistent(film);
    	} finally {
    		pm.close();
    	}
    }
    
    /**
     * Function to create all the films at first time. Once it's executed, it's no more required
     */
    public static void createAllFilms() {
  		Film film = null;
  		PersistenceManager pm = PMF.get().getPersistenceManager();
  		try {
  			film = new Film("1492 - CONQUEST OF PARADISE",1992,"RIDLEY SCOTT",111,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The story of Columbus discovering America, beautifully shot in Costa Rica and excellently played by an top-notch cast including Tcheky Karyo, Michael Wincott and Sigourney Weaver as the Queen of Spain. Interestingly the script shows Columbus mercenary side by detailing the deals he wanted in return for discovering this new world before eventually having to return home in disgrace.");
  			pm.makePersistent(film);
  			film = new Film("187",1997,"KEVIN REYNOLDS",88,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The title number is the police code for a homicide, and its heard more than once in this tough ghetto school drama. Samuel L.Jackson (Pulp Fiction / Sphere) plays a teacher who goes to an inner city school to find it completely out of control. After being robbed by one of the pupils he returns, determined to take the law into his own hands. From the director of Robin Hood - Prince Of Thieves.");
  			pm.makePersistent(film);
  			film = new Film("9 1/2 WEEKS",1986,"ADRIAN LYNE",67,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Director Lyne shows his pop video roots in this erotic tale reputedly based on a true story. Basinger falls for stubble-cheeked Rourke and a steamy, sadomasochistic relationship begins. It lasts the period of the title before the intensity gets too much for her.  Joe Cockers version of You Can Leave Your Hat On accompanies a Basinger strip routine and then theres the infamous fridge sequence.");
  			pm.makePersistent(film);
  			film = new Film("976-EVIL II: THE RETURN",1988,"JIM WYNORSKI",189,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Sequel that still finds the ultimate telephone line, the Devils equivalent of an 0898 number, acquiring victims. The head of a high school taps into the line, hoping to receive supernatural powers to help him in his obsessive lust for a young student. Any one who gets in his way suffers a horrible death. With a  supporting role for Brigitte Nielsen as a seductress in league with Satan himself.");
  			pm.makePersistent(film);
  			film = new Film("A BETTER TOMORROW",1986,"JOHN WOO",65,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The film which brought international stardom to star Chow Yun-Fat and director John Woo. A roller-coaster of a ride with brothers on both sides of the law becoming united in their quest for personal revenge. After forger Mark (Chow) is crippled and double crossed by an associate, cop Kit (Cheung) risks his badge to help him. Violent and gripping. Also available as a boxed set with a supplementary documentary and booklet.");
  			pm.makePersistent(film);
  			film = new Film("A BRONX TALE",1993,"ROBERT DE NIRO",197,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","De Niros directorial debut, taken from co-star Palminteris own stage play. De Niro leads a cast of virtual unknown as a hard-working Bronx bus driver, alarmed at his sons fascination with the local underworld figures. But the lad is involved even deeper than he knows and soon hell have to confront the gangsters in an effort to win back his sons respect.");
  			pm.makePersistent(film);
  			film = new Film("A CHILD LOST FOREVER",1993,"CLAUDIA WEILL",111,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Another of the Odyssey labels seemingly endless supply of true-life weepies, this one involves a young woman (Beverly DAngelo from High Spirits) reluctantly giving up her child for adoption. Years later she discovers  that it died in mysterious circumstances at the age of only three and decides to investigate.");
  			pm.makePersistent(film);
  			film = new Film("A FEW GOOD MEN",1992,"ROB REINER",84,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","After the mysterious death of a young Marine in the barracks, a young navy Lawyer (Cruise) is called in to investigate. The further he delves into the mystery the more he is thwarted by the fearsome and unyielding  Colonel Nathan Jessup (Nicholson), a man who knows the truth and is determined to conceal it....");
  			pm.makePersistent(film);
  			film = new Film("A LEAGUE OF THEIR OWN",1992,"PENNY MARSHALL",45,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Loosely based on the true story of the all-womens baseball league which was formed during the war while all the male players were fighting overseas. Concentrating on one team, the Rockford Peaches whose members include Davis, Madonna, and Lori Petty. Broken-down coach Tom Hanks has to knock them into some sort of shape.");
  			pm.makePersistent(film);
  			film = new Film("A LITTLE PRINCESS",1995,"ALFONSO CUARON",94,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Enchanting family story, with a young shy girl being sent to an austere boarding school in New York after her father leaves to go to war. Initially she has a terrible time, being regarded as an outsider, but slowly realises her own self-worth and becomes liked and admired by both the staff and the pupils. Eleanor Bron plays the strict governess.");
  			pm.makePersistent(film);
  			film = new Film("A LOW DOWN DIRTY SHAME",1994,"KEENAN IVORY WAYANS",136,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Cool and sleek comedy thriller directed by and starring IN LIVING COLORs Wayans. Hes the Shame of the name, an ex-cop whose personal vendetta with a drug lord got him thrown off the force. Now a private eye hes given  an opportunity  to get back at the man who wrecked his career. Enjoyable fun with some gripping shoot-outs. Mrs Will Smith, Jada Pinkett co-stars.");
  			pm.makePersistent(film);
  			film = new Film("A NIGHTMARE ON ELM ST. 4",1988,"RENNY HARLIN",197,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Not one of the better outings for Freddy Krueger, being little more than a series of admittedly spectacular special effects sequences. Here hes still tormenting a group of teenagers through their dreams, but may have met his match in a girl with telekinetic powers. Each murder is capped off with the usual one-liners. Director Renny Harlin went on to direct Die Hard 2, Cliffhanger and The Long Kiss Goodnight.");
  			pm.makePersistent(film);
  			film = new Film("A NIGHTMARE ON ELM ST. PART 2",1985,"JACK SHOLDER",58,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Confused sequel with the spirit of Freddy Kruger coming back to possess a young teenager (Mark Patton). Soon hes dispatching his enemies, such as a sadistic gym teacher, until Freddy makes his return to the real world and causes havoc at a poolside party. Not the best in the series.");
  			pm.makePersistent(film);
  			film = new Film("A NIGHTMARE ON ELM STREET",1984,"WES CRAVEN",137,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The one that started the long-running Freddy Krueger series and still the best. When a group of teenagers start to have dreams about a scarred killer wearing a glove with blades on the fingers, they do not know that he is coming back for revenge for being murdered by their parents years before. When the kids start to die one girl tries to unravel the horrifying mystery of his identity. A very early performance from a young Johnny Depp.");
  			pm.makePersistent(film);
  			film = new Film("A NIGHTMARE ON ELM STREET PART 6 - FREDDYS DEAD",1991,"RACHEL TALALAY",152,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The man of your dreams is about to go bye-byes, as he finally gets his comeuppance after taking on his own daughter (somebody never even mentioned in the series so far). Some of the cassettes available included the last reel in 3D, although you need the special glasses. And yes, hes well and truly dead. Until Wes Cravens New  Nightmare that is!!");
  			pm.makePersistent(film);
  			film = new Film("A.P.E.X.",1994,"PHILIP J.ROTH",148,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Okay sci-fi with good ideas but hampered by a pretty obvious lack of budget. A  scientist travels back in time to retrieve an experimental probe but unwittingly  infects the present with a virus. When he goes back to the future the plague has decimated mankind, and hunter / killer robots roam the wastelands.  Decent effects considering the money available, but its pretty obvious theyve only got three robot suits at any one time.");
  			pm.makePersistent(film);
  			film = new Film("A PERFECT WORLD",1993,"CLINT EASTWOOD",87,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Costner is a prison escapee who takes a young boy as hostage in order to get across state lines in a stolen car and Clint is the Sheriff on his trail in this absorbing drama. As they proceed the crook and the boy start to respect and even like each other, but the cops are gaining mile by mile, with orders to shoot to kill...");
  			pm.makePersistent(film);
  			film = new Film("A RAGE IN HARLEM",1991,"BILL DUKE",109,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Very entertaining period comedy drama set in the 50s, taken from the book by  Chester Himes. Ex-Mrs Mike Tyson Robin Givens hides out in Harlem with a stash of stolen gold and tries to hang onto it while being hunted by everyone from the Mob owners of the loot to Hines as a phony  priest. Danny Glover is superb in a small role as a tough gangster totally devoted to his tiny pet poodle. Terrific soundtrack too.");
  			pm.makePersistent(film);
  			film = new Film("A RIVER RUNS THROUGH IT",1992,"ROBERT REDFORD",84,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Slightly rambling but thoroughly enjoyable family saga, with Tom Skeritt teaching his sons the virtues theyll need for later life, as well as instilling in them a love of fly-fishing. The boys (Pitt and Craig Sheffer) eventually leave home but one of them is going to be seduced by the vices of the big city, leading to a tragic end.  Great performances all round including Brenda Blethyn as the boys mother.");
  			pm.makePersistent(film);
  			film = new Film("A SIMPLE WISH",1997,"MICHAEL RITCHIE",51,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Childrens fantasy starring Mara Wilson from Matilda. She plays the daughter of one of Central Parks horse drawn cab drivers who longs for a fairy godmother to grant her special wish for her dad. However, the character who appears with a magic wand is Murray (Martin Short), the least qualified fairy godmother on the block. Lots of wild special effects and with Kathleen Turner as an evil witch.");
  			pm.makePersistent(film);
  			film = new Film("A THIN LINE BETWEEN LOVE AND HATE",1996,"MARTIN LAWRENCE",125,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The directorial debut of comedian Martin Lawrence  (Bad Boys, Nothing To Lose). Fatal Attraction played for laughs with Lawrence having a one-night stand with Whitfield and then finding she thinks one night is not enough and wants more of him - at gunpoint if necessary. His comedy comes across much better in his stand-up performance film You So Crazy.");
  			pm.makePersistent(film);
  			film = new Film("A TIME TO KILL",1996,"JOEL SCHUMACHER",113,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Based on another John Grisham bestseller. Matthew McConaughey plays a Southern lawyer who takes on the case of a black man who has killed his daughters rapists. As the racial divide splits the town and threatens him and his family, help comes in the form of law student Sandra Bullock. Co-starring Samuel L.Jackson and Kevin Spacey.");
  			pm.makePersistent(film);
  			film = new Film("A VIEW TO A KILL",1985,"JOHN GLEN",150,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Not the best movie in the series with which Moore to choose to end his tenure of the 00 prefix but it has its moments in the set-pieces and stunts. Christopher Walken is a genetically-perfect psychopath, created via a test-tube, whose plan is to destroy Californias Silicone Valley thus leaving his company as the only source of computer technology. Grace Jones and Tanya Roberts are not memorable Bond girls either.");
  			pm.makePersistent(film);
  			film = new Film("A.W.O.L. - ABSENT WITHOUT LEAVE",1990,"SHELDON LETTICH",50,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A Foreign Legionnaire throws his kepi away and enters the world of illegal fighting in this formula Van Damme offering. With the usual motive of wanting revenge for the murder of his brother he takes on all comers in repeated fights to the death  (this is now a feature of Van Damme films from Bloodsport to The Quest). Must be the first film in which a Scotsman kickboxes while wearing a kilt.....");
  			pm.makePersistent(film);
  			film = new Film("A WALK IN THE CLOUDS",1995,"ALFONSO ARAU",82,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Moody  love story which is beautifully filmed. Reeves plays a soldier who returns home after the war to find his wife has changed and the passion between them extinguished. On the road as a salesman he meets the sultry Aitana Sanchez-Gijon, the pregnant daughter of a wealthy landowner, and agrees to pretend to be her husband to save her honour. From the maker of Like Water For Chocolate.");
  			pm.makePersistent(film);
  			film = new Film("A WOMAN SCORNED",1993,"ANDREW STEVENS",60,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","After her husband commits suicide after the collapse of his business, a woman (Shannon Tweed - No Contest) decides to turn the tables on the man she holds responsible (director Stevens). She enters his household posing as a tutor for his teenage son and sets about seducing all the members of his family, turning them against each other. The inevitable sequel followed.");
  			pm.makePersistent(film);
  			film = new Film("ABOVE THE RIM",1994,"JEFF POLLACK",174,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Street basketball is the focus of this character-driven drama concerning a young student whose college future is threatened when his basketball skills get him the offer of fast money and scams in games. Not as many laughs as the Snipes/Harrellson pic White Men Cant Jump,");
  			pm.makePersistent(film);
  			film = new Film("ABSOLUTE POWER",1996,"CLINT EASTWOOD",171,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Clint plays a cat burglar with ambition. While robbing the White House (no less) he witnesses a murder, the killer being the President himself. Does he keep the information to himself or go public and risk his life. Strong support from Ed Harris (The Abyss), Judy Davis (Husbands And Wives), Scott Glenn (Backdraft) and Laura Linney (Primal Fear).");
  			pm.makePersistent(film);
  			film = new Film("ACCIDENTAL HERO",1992,"STEPHEN FREARS",133,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Satirical comedy about the value of fame, with Hoffman as a down-and-out who rescues survivors from a plane crash, then leaves the scene. When the TV starts to send out appeals to find The Angel of Flight 104  an impostor turns up in the form of Andy Garcia. Hes hailed as a hero while Hoffmans luck hits rock bottom.");
  			pm.makePersistent(film);
  			film = new Film("ACE VENTURA: PET DETECTIVE",1994,"TOM SHADYAK",110,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Alrighty then! The movie which catapulted Carrey to stardom, featuring him as the title character, a  private tec dedicated to animal causes and on the trail of a missing dolphin, mascot of the Miami Dolphins football team. Co-stars Courtney Cox from TVs Friends.");
  			pm.makePersistent(film);
  			film = new Film("ACE VENTURA: WHEN NATURE CALLS",1994,"STEVE OEDEKERK",112,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The detective with animal instincts strikes again, this time travelling to Africa to save the assorted flora and fauna from a gang of merciless poachers. Be prepared for the standard array of Carrey grinning, making funny faces and doing quite revolting things with food.");
  			pm.makePersistent(film);
  			film = new Film("ACTION JACKSON",1988,"CRAIG R.BAXLEY",191,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Carl Weathers is the title character, a cop with a reputation so fearsome that suspects faint when he walks into the room. After busting the son of a rich industrialist (Craig T.Nelson) he becomes the mans sworn enemy. The ruthless tycoon murders his own wife (Sharon Stone) and tries to frame Jackson for the crime. Cracking action thriller from director Craig R.Baxley (Dark Angel).");
  			pm.makePersistent(film);
  			film = new Film("ADDAMS FAMILY VALUES",1993,"BARRY SONNENFELD",99,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Julia and Huston return for this sequel based on the hit TV series taken from the macabre cartoons of Charles Addams. This time an evil gold-digger (Joan Cusack) has set her sights on wooing Uncle Fester (Christopher Lloyd), but her mind is firmly set on the fabled Addams family treasure, hidden somewhere within the cavernous mansion. Features Addams Groove by MC Hammer.");
  			pm.makePersistent(film);
  			film = new Film("ADDICTED TO LOVE",1997,"GRIFFIN DUNNE",41,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Wickedly black comedy which is a warning to anyone whos dumped a lover. Ryan and Broderick are left on the shelf after their respective lovers, Tcheky Karyo and  Kelly Lynch, have left them and set up home together. Both Broderick and Ryan want their exs back and are spying on the couples new apartment when they spot each other and decide to hatch a particularly evil plan that will drive the couple apart.");
  			pm.makePersistent(film);
  			film = new Film("ADRENALIN",1997,"ALBERT PYUN",189,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Christopher Lambert teams up with Natasha Hendstridge of Species in this breakneck sci-fi thriller from prolific director Pyun. The world of the year 2007 is in peril from a virus caused by a toxic chemical leak, and cops Lambert and Henstridge have to pursue an infected mass killer who has the power to infect others. They have until dawn to trap him and kill him.");
  			pm.makePersistent(film);
  			film = new Film("AFTERBURN",1992,"ROBERT MARKOWITZ",142,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Based on the true story of Janet Harduvel, a determined Air Force widow who took on one of the biggest corporations in America. After her husbands F-16 fighter crashes and he is killed, the official explanation is pilot error. She refuses to believe this, and takes on military contractors General Electric in an effort to clear her late husbands name. Gripping drama, with Michael Rooker (Cliffhanger) and Vincent Spano (Blood Ties).");
  			pm.makePersistent(film);
  			film = new Film("AGAINST THE WALL",1994,"JOHN FRANKENHEIMER",104,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Violent and very brutal drama revolving around the Attica prison riot and siege. A constantly simmering powder keg of a prison, the place finally erupted in 1971 after a riot in which guards were taken hostage and other prisoners tortured and murdered as feuds and internal squabbles were settled in savagery. Kyle MacLachlan is the captured guard at the centre of the story and Samuel L.Jackson the Black Panther leader of the revolt.");
  			pm.makePersistent(film);
  			film = new Film("AIR FORCE ONE",1997,"WOLFGANG PETERSEN",52,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Taut and exciting action thriller with Harrison Ford as a surprisingly plausible President of the USA, trapped aboard the official plane when it is taken over by dedicated terrorists, led by a maniacal Gary Oldman. They want the release of a rebel Chechyan leader or they will kill everyone on the plane, beginning with the Presidents family. Corking stuff from the director of In The Line Of Fire.");
  			pm.makePersistent(film);
  			film = new Film("AIRHEADS",1994,"MICHAEL LEHMANN",69,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A quite dreadful garage band burst into a radio station with toy guns to try to get their demo tape played on the air, but the stunt goes badly wrong and turns into a siege situation with a DJ being taken hostage. Soon theyre not only on the radio but the TV as well! Comedy with a few neat points about the media.");
  			pm.makePersistent(film);
  			film = new Film("ALADDIN",1992,"RON CLEMENTS & JON MUSKER",149,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Another mammothly successful animated offering from Disney, an Arabian romp with the central character finding a magic lamp and releasing the Genie trapped within who gives him three wishes. Armed with these, and the eternally wise-cracking, shape-changing  Genie (voiced by Robin Williams) at his side he takes on the evil Jafar and tries to win the hand of the beautiful Princess Yassmin.");
  			pm.makePersistent(film);
  			film = new Film("ALADDIN - THE RETURN OF JAFAR",1993,"Director unlisted",177,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A straight-to-video sequel to Disneys Aladdin which suffers from the lack of the vocal talents of Robin Williams. The plot has the evil Jafar released from the lamp in which he has been imprisoned and threatening all those who helped Aladdin in the first and far superior instalment. Voices by nobody youve ever heard of.");
  			pm.makePersistent(film);
  			film = new Film("ALASKA",1996,"FRASER C.HESTON",77,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Fraser C. Heston directs his dad and Monkey Trouble star Thora Birch in this family-oriented outdoors adventure. Having moved his family to a small Alaskan town after the death of his wife, their father (Dirk Benedict) is injured when his light plane crashes miles from home. While his children are searching for him they also have to evade a gang of poachers who are hunting bear cubs.");
  			pm.makePersistent(film);
  			film = new Film("ALBINO ALLIGATOR",1997,"KEVIN SPACEY",136,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Oscar-winner Kevin Spacey  (The Usual Suspects / L.A. Confidential) directs but does not appear in this taut thriller. After a bank robbery goes wrong, three desperate criminal find themselves holed up in a dingy basement bar. As the time drags, not knowing if the police are on their trail, their motivations and past failures come to the fore. Character driven drama with the return to the screen of Faye Dunaway.");
  			pm.makePersistent(film);
  			film = new Film("ALIEN",1979,"RIDLEY SCOTT",87,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The original and many believe still the best, the terrifying tale of what happens when the crew of the spaceship Nostromo are revived to answer a distress call from a nearby planet, and soon take on an unwelcome extra passenger. Brilliant direction and suspense, with design by Swiss artist  H.R.Giger and a strong cast including Tom Skerritt, John Hurt, Veronica Cartwright,  Harry Dean Stanton and Jones the cat.");
  			pm.makePersistent(film);
  			film = new Film("ALIEN 3",1992,"DAVID FINCHER",148,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Third outing for Sigourney Weaver as Ripley. This time her space escape pod  lands on an inhospitable planet used as a space penal colony. The prisoners and warders ignore her warnings about the Aliens, until.......qqqVery dark and sombre.");
  			pm.makePersistent(film);
  			film = new Film("ALIEN NATION",1988,"GRAHAM BAKER",119,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A sci-fi thriller with political undertones. After a spacecraft crash lands on Earth with several hundred thousand aliens, relatively human in appearance, they are slowly assimilated into society but suffer discrimination. When a series of murders occurs in the alien community, one of their number is paired with resentful human cop James Caan to investigate. With Terence Stamp as a successful alien businessman. Followed by a TV series.");
  			pm.makePersistent(film);
  			film = new Film("ALIEN SPECIES",1995,"DAVE PAYNE",110,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Alien underground as a bunch of genetic scientists start dabbling with something they shouldnt and come up with the inevitable clawed, multi-toothed dripping nasty. When it gets out theyre trapped five miles underground in the labyrinth of tunnels surrounding their secret lab. Not exactly original but one for the Maria Ford (Final Judgment / Ring Of Fire) fans");
  			pm.makePersistent(film);
  			film = new Film("ALIENS: SPECIAL EDITION",1986,"JAMES CAMERON",155,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The Special Edition of Camerons sci-fi masterpiece is the version he wanted to release originally but was cut for time considerations. Extra scenes include the Aliens attacking the colonists at the beginning and the marines setting up booby traps for the voracious killers. About   17  minutes longer than the first release.");
  			pm.makePersistent(film);
  			film = new Film("ALIVE",1993,"FRANK MARSHALL",83,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Inspiring story of the Andes air crash, where members of a sports team were stranded after their plane hit a mountain. When the supplies ran out they had to make a horrifying decision - to die of starvation or break the ultimate taboo and eat the flesh of their dead friends and companions.");
  			pm.makePersistent(film);
  			film = new Film("ALL DOGS GO TO HEAVEN",1989,"DON BLUTH",73,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Childrens animation with a few forgettable songs rendered by Melba Moore. A dog who has died must return to earth and perform a good deed before hell be let into Heaven.Voices include Burt Reynolds, Lori Anderson and Dom De Luise");
  			pm.makePersistent(film);
  			film = new Film("AMBUSH IN WACO",1993,"DICK LOWRY",72,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The true story of the siege of the David Koresh cult, the Branch Davidians at their heavily fortified headquarters at Waco, Texas. An unsuccessful musician, Koresh turned his back on his strict religious upbringing and formed his own cult, attracting the weak through the force of his own personality. When the Federal forces tried to enter his compound, the first shots rang out....");
  			pm.makePersistent(film);
  			film = new Film("AMERICAN SAMURAI",1992,"SAM FIRSTENBERG",104,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Capable action time-passer with Bradley as the adopted son of a Samurai who inherits the family ceremonial sword following  the death of his beloved father. Soon he discovers that his brother has dealing with the Japanese Yazuza and illegal to-the-death sword fights. Bradley is the star of American Ninja 3 - 5 and the Cyborg Cop series, while action co-star Mark Dacascos has been seen in  D.N.A. and Crying Freeman.");
  			pm.makePersistent(film);
  			film = new Film("AMERICAN SHAOLIN",1992,"LUCAS LOWE",104,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Hong Kong movie with American principle players. A young man is determined to become the best martial artist in the world after a series of defeats, so travels to China to study at the famous Shaolin Temple. Initially rejected by the monks, his sheer persistence impresses them and they admit him, subjecting him to relentless training. You know the rest.");
  			pm.makePersistent(film);
  			film = new Film("AMERICAN YAKUZA",1994,"FRANK CAPPELO",168,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Superb action thriller with a good script and a brain behind the plot. An ex-convict is inducted in the Japanese Mafia, the Yakuza, after saving one of their heads from a beating. He rises through the ranks, falling for the daughter of one of the top men, but actually hes a deep cover cop sent in to infiltrate the secret organisation. But now his loyalties are becoming divided. Excellent action with great twists.");
  			pm.makePersistent(film);
  			film = new Film("AMERICAN YAKUZA 2 - BACK TO BACK",1996,"ROGER NYGARD",168,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A sequel in name only, this sees ex-cop Michael Rooker and his rebellious daughter (Danielle Harris from the later Halloween films) taken hostage by a Japanese Yakuza after the gangster is betrayed by American mobsters. Eventually finding out that the Mob are in league with a corrupt officer who threw him off the force Rooker and Ishibashi team up for an explosive face-off. Heavy firearms, great lines and non-stop action.");
  			pm.makePersistent(film);
  			film = new Film("AMITYVILLE DOLLHOUSE",1996,"STEVE WHITE",136,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A possessed dolls house is the latest receptacle for evil in this further sequel. After moving into a new house, a remarried couple discover the toy of the title. Giving it to their youngest daughter, strange things start to happen. Whatever happens in the little building happens in reality. Some good Hell effects come the climax. The films no longer claim to be based on the original book detailing the horrors experienced by the Lutz family");
  			pm.makePersistent(film);
  			film = new Film("AMONGST FRIENDS",1993,"ROB WEISS",138,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Low budget thriller from debut director Robert Weiss. Three friends flirt with crime until one of them is arrested and sent to jail. On his release he tempts them with the knowledge he has picked up inside and plans a major drug deal. Inevitably the three start to fall out as the event gets nearer.");
  			pm.makePersistent(film);
  			film = new Film("AMOS & ANDREW",1993,"E. MAX FRYE",79,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A good cast, including Michael Lerner from Barton Fink and 9 To 5s Dabney Coleman are generally wasted in this racial comedy. Prize-winning black playwright Samuel L.Jackson moves into an upscale all-white neighbourhood and is taken for a burglar by the racist locals. When the police chief tries to cover the racism up by bringing in real ex-convict Nicolas Cage things get even more complicated.");
  			pm.makePersistent(film);
  			film = new Film("AN EYE FOR AN EYE",1995,"JOHN SCHLESINGER",102,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The lack of justice forces a mother to take the law into her own hands in this drama from acclaimed British director Schlesinger. When the murderer of her daughter is released on a technicality and theres nothing the justice system can do about it, Sally Field gets herself a gun and goes to enforce the Biblical system of an eye for an eye. With Ed Harris, Joe Mantegna and Beverly DAngelo.");
  			pm.makePersistent(film);
  			film = new Film("ANACONDA",1997,"LUIS LLOSA",71,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Hokum with an Amazonian anthropological expedition being hijacked by the sinister shipwrecked Jon Voight, a hunter after a 40-foot anaconda reputed to be lurking in that stretch of the river. Great effects and some scares, especially when the snake gets hungry. With Eric Stoltz (Memphis Belle) , Ice Cube, Jonathan Hyde (Titanic), Kari Whurer (Red-Blooded) and Danny Trulo (Heat).");
  			pm.makePersistent(film);
  			film = new Film("AND THE BAND PLAYED ON",1993,"ROGER SPOTTISWOODE",172,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Two and a half hour drama taken from the acclaimed book by Randy Shilts, detailing the spread of the AIDS virus through America told through the eyes of doctors, researchers and the sufferers themselves. Cast for this worthy and serious production includes Phil Collins, Alan Alda, Ian McKellen, Richard Gere, Glenne Headly , Lily Tomlin and French actress Nathalie Baye.");
  			pm.makePersistent(film);
  			film = new Film("ANDRE",1994,"GEORGE MILLER",125,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Perfect family entertainment with Tina Majorino (from Waterworld) as the daughter of a family who adopt an orphaned seal cub. When it grows to full size they try to return it to the wild but theres a problem - it doesnt want to go!");
  			pm.makePersistent(film);
  			film = new Film("ANGEL HEART",1987,"ALAN PARKER",69,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Stylish horror with a film noir  flavour. Battered private eye Mickey Rourke takes on a job of finding a missing crooner, lost somewhere on the shady side of New Orleans. Hired by Mr. Lou Cypher (geddit, geddit?) hes soon involved in all kinds of and almost everyone he talks too meets a sticky end. Very watchable but  very complex and disturbing. Based on the book Falling Angel by William Hjortsberg.");
  			pm.makePersistent(film);
  			film = new Film("ANGEL OF FURY",1992,"DAVID WORTH",91,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Standard Rothrock action outing, shot in Malaysia. She plays a security expert, the target of terrorists who attack her and kill her husband. Slowly recovering and regaining her fighting skills, she knows that she was targeted for a reason -  the revolutionary computer system technology her company is working on. Sam Jones, Flash Gordon back in the 80s, stars as one of Dragos henchmen.");
  			pm.makePersistent(film);
  			film = new Film("ANGELS",1994,"WILLIAM DEAR",47,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A young boy whos family has split up believes that if his struggling local baseball team can win the league his mother and father will be reconciled. After a lot of praying it seems that the team is getting help from above. A remake of the 1951 film  Angels In The Outfield. With Brenda Fricker (My Left Foot) and Christopher Lloyd (from the Back To The Future series).");
  			pm.makePersistent(film);
  			film = new Film("ANIMAL INSTINCTS",1992,"GREGORY HIPPOLYTE",82,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","One of the many erotic thrillers which followed in the steamy wake of Basic Instinct. A  couples marriage goes haywire when the wife turns into a raging nymphomaniac after taking anti-depressant pills.  Followed by several sequels linked by title only.");
  			pm.makePersistent(film);
  			film = new Film("ANIMAL INSTINCTS 2",1993,"GREGORY HIPPOLYTE",68,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","That naughty man Hippolyte strikes again with another Basic Instinct  inspired erotic thriller. A psychiatrist dealing in sexual dysfunction gets involved with a patient in the pleasing form of Shannon Whirry and - as often happens in this sort of thing - gets involved with murder. Also appearing are Sandahl Bergman from Conan The Barbarian and Richard (Shaft) Roundtree.");
  			pm.makePersistent(film);
  			film = new Film("ANOTHER 48 HRS.",1990,"WALTER HILL",56,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Disappointing sequel reuniting Nolte and Murphy as the cop and the con man. Nolte has to ask Murphy for help once more after a gang of cop killers start to take out officers on the streets of the city. Nolte knows its tied in to a drug deal and a corrupt officer. Large-scale fights and set-pieces but a lot of the humour seems very forced.");
  			pm.makePersistent(film);
  			film = new Film("ANOTHER STAKEOUT",1993,"JOHN BADHAM",194,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Dreyfuss and Estevez are joined by  Rosie ODonnell and a dog in this belated sequel to the first. Seven years down the line sees them staking out a potential witness in a Mob trial. Not as sharp or snappy as the first despite some good lines.");
  			pm.makePersistent(film);
  			film = new Film("APOLLO 13",1996,"RON HOWARD",121,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The true story of the disastrous Apollo mission with the unlucky name. On their way to the moon, astronauts Lovell, Haise and Swigart (Hanks, Paxton and Kevin Bacon) are all but marooned when a vital pump in their craft explodes. With no hope of a rescue mission they have to try to somehow repair the ship.");
  			pm.makePersistent(film);
  			film = new Film("ARACHNOPHOBIA",1990,"FRANK MARSHALL",145,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Anybody suffering from the title complaint (a fear of spiders) should steer well clear of this! A small town gets menaced by an infestation of killer spiders after one enters the country  from South America. Soon Jeff Daniels and mad bug exterminator John Goodman are desperately trying to save the town from the hairy little blighters.");
  			pm.makePersistent(film);
  			film = new Film("ARCTIC BLUE",1995,"PETER MASTERTON",159,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Video favourite Rutger Hauer goes on the ice as a marshal detailed to escort a vicious criminal (Walsh)  to jail. When their transport crashes they find themselves trapped in the arctic waste, and have to trust each other when it seems someone is out to silence Walsh for what he knows. Fine photography of real locations adds to the authentically chilly feel of the piece.");
  			pm.makePersistent(film);
  			film = new Film("ARMY OF DARKNESS",1992,"SAM RAIMI",164,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The third instalment in Raimis EVIL DEAD series and an absolute romp as the hapless Ash (Campbell) stranded in the Middle Ages after his last encounter with the Deadites. Hailed as a god by the populace, he has to save the castle from an evil force but predictably gets the incantation wrong, allowing the Deadites to rise again.");
  			pm.makePersistent(film);
  			film = new Film("AROUND THE WORLD WITH TIMON AND PUMBAA",1996,"Director unlisted",140,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A compilation from the Disney Channel, featuring the Marquette Timon and the warthog Pumbaa from the mega-hit The Lion King. Voiced by Nathan Lane (The Birdcage / Mouse Hunt) and Ernie Sabella, they travel around the world, entertaining younger children and managing to throw some educational material their way at the same time.");
  			pm.makePersistent(film);
  			film = new Film("ARTICLE 99",1992,"HOWARD DEUTCH",169,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Comedy drama set at a hospital for Vietnam veterans. Ray Liotta and Kiefer Sutherland are two young interns trying to battle the bureaucracy which is seemingly dedicated to cost-cutting and penny-pinching with few concerns for the veterans themselves. Strong performances from Forest Whitaker as a bitter invalid and John Mahoney (from TVs Frasier) as one of the supervisors.");
  			pm.makePersistent(film);
  			film = new Film("ASSASSINS",1995,"RICHARD DONNER",64,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Stallone is a respected professional in his chosen field - assassination. Planning to retire from the field he finds theres another killer on the block, a edgy paranoid (Antonio Banderas) who not only wants to be the number one man but also to wipe out any opposition - including Stallone. From the director of the Lethal Weapon series.");
  			pm.makePersistent(film);
  			film = new Film("ATTACK OF THE 50FT. WOMAN",1994,"CHRISTOPHER GUEST",95,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Comedy remake of the 50s sci-fi picture which was much funnier, even if it was mostly unintentional. Daryl Hannah (Splash / Legal Eagles) plays a woman whose husband is seeing another woman and whose father (William Windom) looks down on her. After an encounter with a flying saucer she soon starts to grow, and grow, and grow. Now, predictably,  its payback time. Originally made for cable.");
  			pm.makePersistent(film);
  			film = new Film("AUSTIN POWERS: INTERNATIONAL MAN OF MYSTERY",1997,"JAY ROACH",82,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Glorious send-up of 60s spy movies with Myers playing both the title role and the villain of the piece, Dr. Evil. Returning to Earth after being frozen in space, Dr. Evil has various evil schemes, but also defrosted from cryo-sleep is Austin Powers, a swinging 60s icon with terrible teeth, crushed velvet suits in a variety of revolting colours and some very non-90s attitudes. Very accurate and constantly entertaining.");
  			pm.makePersistent(film);
  			film = new Film("AWAKENINGS",1990,"PENNY MARSHALL",85,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Powerful performances drive this remarkable drama, based on a true-life occurrence in the life of psychologist Dr.Oliver Sacks. Williams plays a fictionalised version of Sacks who discovers that patients previously thought to be in irreversible comas could be revived by  use of an experimental drug. But the effects are not permanent. De Niro plays a man revived after 30 years and begins to discover love before the side effects kick in.");
  			pm.makePersistent(film);
  			film = new Film("BABE",1995,"CHRIS NOONAN",140,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Charming and warm story to appeal to adults and children alike, with amazing effects making the talking animals totally believable. Babe is a pig raised by a border collie, and who has the abilities of a sheepdog, so the kindly farmer who owns him decides to enter him in competition. Huge fun, based on the childrens best-seller by Dick King-Smith.");
  			pm.makePersistent(film);
  			film = new Film("BABYS DAY OUT",1994,"PATRICK READ JOHNSON",83,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Clever and very visual family comedy from John Hughes, maker of the Home Alone series, in which a young baby  is snatched away from a rich couple by three crooks. When baby manages to crawl out of a window and happily crawl all over such places as a building site with the trio in pursuit theres gags and stunts galore as the three are mercilessly pounded and pummelled.");
  			pm.makePersistent(film);
  			film = new Film("BACKBEAT",1994,"IAIN SOFTLEY",116,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The heady days of the pre-fame Beatles in Hamburg are lovingly detailed in this musical bio-pic. The real focus is on Stuart Sutcliffe and his relationship with German photographer Astrid Kirchner, who was responsible for the look of the band. Music rights problems meant that no Beatles tracks could be used. The soundtrack comprises covers of the songs of the time and Beatles-style compositions by Don Was.");
  			pm.makePersistent(film);
  			film = new Film("BACKDRAFT",1991,"RON HOWARD",131,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Hot action with the fire brigade as a demented arsonist is setting traps leading to the explosive firestorms of the title. Meanwhile the boys in the brigade have to deal with their tangled love lives and complicated family problems. Strong cast includes Donald Sutherland and Scott Glenn.");
  			pm.makePersistent(film);
  			film = new Film("BAD BOYS",1995,"MICHAEL BEY",108,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","High-speed thrills and mayhem as cops Will Smith and Martin Lawrence go after the murderous psycho Tcheky Karyo. Much running around, guns going off and fantastic car chases. Also features Tea Leoni from TVs The Naked Truth.");
  			pm.makePersistent(film);
  			film = new Film("BAD COMPANY",1995,"DAMIEN HARRIS",108,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Complex thriller overstretching its thin plot a little with Fishburne (Event Horizon) playing a CIA agent who infiltrates an industrial espionage ring planning to steal military secrets. His objectivity is compromised when he falls for a fellow conspirator in the form of Ellen Barkin. With Frank Langella and model turned actress Gia Carrides.");
  			pm.makePersistent(film);
  			film = new Film("BAD GIRLS",1994,"JONATHAN KAPLAN",174,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A Western with a different slant, as four hookers turn outlaw when one of them kills a nasty customer, then find out that the bank where theyve been stashing their money has been robbed. Time for the girls to go after the robbers. MacDowell, Stowe, Mary Stuart Masterton and drew Barrymore are the female gunslingers and James Russo and Robert Loggia the baddies in their sights in this not totally successful production.");
  			pm.makePersistent(film);
  			film = new Film("BAD INFLUENCE",1990,"CURTIS HANSON",186,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Spader is about to get pummelled in a barroom fight when Lowe intervenes to save him from a beating. Hes naturally grateful, but soon control-freak Lowe is intruding on all aspects of Spaders life, trying to take it over. From the director of The Hand That Rocks The Cradle and L.A. Confidential.");
  			pm.makePersistent(film);
  			film = new Film("BAD LIEUTENANT",1992,"ABEL FERRERA",48,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Keitel is mesmerising as the unnamed title character, an immoral, heavy-drinking,drug-taking beast of a homicide cop, deeply embroiled in gambling and the drug scene, who finds a path of possible salvation if he can find the youths who raped a young nun who refuses to press charges. Almost too unbearable to watch in parts.qqqFrom the director of Driller Killer and Angel Of  Vengeance, so you have been warned.");
  			pm.makePersistent(film);
  			film = new Film("BALTO",1995,"SIMON WELLS",122,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","An animated feature produced by Steven Spielberg. Set in the frozen wastes of Alaska in the mid-20s, Balto is a half-wolf, half-husky  who is rejected by  other wolves and dogs. When a serious disease breaks out in an isolated town, Balto is the one who can make the long trek with vital medicine. An impressive cast of voice talent includes Kevin Bacon, Phil Collins, Bob Hoskins, Bridget Fonda, and Donald Sinden.");
  			pm.makePersistent(film);
  			film = new Film("BAMBI",1942,"DAVID D.HAND",105,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","One of the all-time Disney classic, the story of the young deer left alone after hunters in the forest kill his mum. There wont be a dry eye in the house at this point. Easily one of the best example of the Golden Age of Disney animation.");
  			pm.makePersistent(film);
  			film = new Film("BARB WIRE",1995,"DAVID HOGAN",121,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Dont Call Me Babe!, she commands, but what you can call the film is a thinly disguised  remake of Casablanca set in the future. Enjoyably daft nonsense which doesnt take itself too seriously. The video version contains additional footage at the beginning of Pammy in the shower but, regrettably, not her wedding video.");
  			pm.makePersistent(film);
  			film = new Film("BASIC INSTINCT",1992,"PAUL VERHOVEN",88,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Controversial erotic thriller with Sharon Stone as the chief suspect in a series of ice pick murders. When cop Michael Douglas is assigned to the case he starts to become obsessed by her. As the bodies mount up, so do Stone and Douglas.");
  			pm.makePersistent(film);
  			film = new Film("BASIL THE GREAT MOUSE DETECTIVE",1986,"JOHN MUSKER & RON CLEMENTS",198,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A terrific idea, a mousey version of Sherlock Holmes with Basil a rodent detective living under Baker Street. Hes on the trail of a toymaker, believed kidnapped by his arch-enemy Rattigan (voiced with relish by horror veteran Vincent Price). One of the first animation features to use computer graphics for backgrounds.");
  			pm.makePersistent(film);
  			film = new Film("BATMAN",1989,"TIM BURTON",46,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Dark and powerful version of the DC Comics character  from Edward Scissorhands director Burton. Michael Keaton is Bruce Wayne, millionaire playboy who is also the dark avenger Batman. When a small-time criminal is scarred by acid and reemerges as the demented Joker (Nicholson), Batman must stop the crime spree the maniac is inflicting on Gotham City. Great production design and striking visuals. Three sequels followed.");
  			pm.makePersistent(film);
  			film = new Film("BATMAN AND ROBIN",1997,"JOEL SCHUMACHER",74,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","George Clooney straps on the Bat-codpiece and teams up with Robin (Chris ODonnell) and new recruit Batgirl (Alicia Silverstone) in order to save Gotham City from the triple threat of Mr. Freeze (Arnie), Poison Ivy  (Uma Thurman) and the monstrous Bane. As usual the effects and set-pieces are first class.");
  			pm.makePersistent(film);
  			film = new Film("BATMAN FOREVER",1995,"JOEL SCHUMACHER",195,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Val Kilmer steps into the Bat-costume for the only time as he prepares to save Gotham City from the combined threat of The Riddler (Carrey) and Two-Face (Tommy Lee Jones), while also dealing with the beautiful Dr.Chase Meridian (Nicole Kidman) and taking on a sidekick in the form of Robin (Chris ODonnell).");
  			pm.makePersistent(film);
  			film = new Film("BATMAN RETURNS",1992,"TIM BURTON",72,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The darkest and most inventive of the series, with Keatons caped crusader tangling with both the gross and deformed Penguin (Danny DeVito) and the alluring Catwoman (Pfeiffer) between whom there is a strong attraction. The usual fantastic production design and with a cast including Christopher Walken as crazed megalomaniac Max Schreck and Michael Gough as the devoted and resourceful Alfred.");
  			pm.makePersistent(film);
  			film = new Film("BEAN: THE ULTIMATE DISASTER MOVIE",1997,"MEL SMITH",56,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Bean speaks! Rowan Atkinson brings his shambling creation to the movies in this knockabout farce. Everything art museum guard Bean does is a total disaster, so what else can you expect when he is asked to escort the priceless painting Whistlers Mother over to the States for an exhibition. A showcase for Atkinsons rubber-limbed cavortings and extraordinary range of facial expressions and bodily functions..");
  			pm.makePersistent(film);
  			film = new Film("BEAUTIFUL GIRLS",1995,"TED DEMME",183,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Ensemble comedy with a group of friends at a high school reunion remembering all their ambitions and long lost dreams. But the memories lead to some surprising repercussions for some of the friends. With Uma Thurman (Batman And Robin), Timothy Hutton (Daniel), Rosie ODonnell (The Flintstones), Michael Rapaport (Metro) and Mira Sorvino (The Replacement Killers).");
  			pm.makePersistent(film);
  			film = new Film("BEAUTY AND THE BEAST",1991,"GARY TROUSDALE & KIRK WISE",69,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","One of the best Disney films ever, a superb retelling of the story of the young woman sent to a gloomy castle occupied by a fearsome-looking beast. But looks arent everything and once she realises the tender person underneath the frightening appearance she falls in love with him, freeing him from the curse which made him into the monster. With the voices of Angela Lansbury and Robby Benson.");
  			pm.makePersistent(film);
  			film = new Film("BEAVIS AND BUTT-HEAD DO AMERICA",1997,"MIKE JUDGE",76,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The two snickering, sex-obsessed morons from MTV get involved in a quest travelling across America in this feature-length outing following some misunderstood instructions from a gangland boss. Fans will think its hilarious. Others will just think it puerile. With the voice of Robert Stack.");
  			pm.makePersistent(film);
  			film = new Film("BED OF ROSES",1995,"MICHAEL GOLDENBERG",131,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Mild romantic comedy which epitomises the word charming, with Slater in unusually romantic mode. Masterson plays a young bank clerk who suddenly becomes inundated by bunches of flowers from an unknown admirer. It takes her a while to realise that the source is Slater, a florist.");
  			pm.makePersistent(film);
  			film = new Film("BEETHOVEN",1992,"BRIAN LEVANT",67,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Puppies are cute and adorable, but they grow into big dogs, and few come bigger than the puppy which grows up to be Beethoven, a 12-stone beast adopted by a family after escaping from an experimental lab. They agree to keep him, not knowing the havoc he can cause.qqqThe kids will want a dog just like him after this one...");
  			pm.makePersistent(film);
  			film = new Film("BEETHOVENS 2ND",1993,"ROD DANIEL",62,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Predictable sequel with the monstrous St.Bernard finding a mate and having puppies. Not wanting to get rid of any at all, the kids start hiding them all round the house. For fans of the first, with Charles Grodin tearing lumps out of his toupee yet again.");
  			pm.makePersistent(film);
  			film = new Film("BEFORE AND AFTER",1996,"BARBET SCHROEDER",68,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Strongly acted drama from the director of Single White Female and Reversal Of Fortune. Meryl is the local paediatrician in a small town. Married to artist Liam Neeson they have a young son (Edward Furlong from Terminator 2) who suddenly becomes a suspect after a young girl is found murdered in a snow drift. When he goes missing the whole town talks this as an indication of guilt and turns against the parents.");
  			pm.makePersistent(film);
  			film = new Film("BENNY AND JOON",1992,"JEREMIAH CHECHNIK",113,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Strange but compassionate love story in which a garage mechanic (Aidan Quinn) takes care of his slightly disturbed sister (Mary Stewart Masterton) and is alarmed when she falls for  an eccentric young man (Depp) who believes he is the reincarnation of Buster Keaton and is much given to mime and silent routines.  Odd but gently moving. From the director of the film version of The Avengers.");
  			pm.makePersistent(film);
  			film = new Film("BEST OF THE BEST",1989,"BOB RADLER",163,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Eric Roberts wants revenge in this action story which spawned two sequels. Wanting to avenge the death of his brother, killed by a Korean martial arts master, he joins the American karate team in order to gain entry to an international contest which will bring him face to face with the Koreans responsible. With small roles for James Earl Jones and Louise Fletcher.");
  			pm.makePersistent(film);
  			film = new Film("BEST OF THE BEST 2",1992,"BOB RADLER",117,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Revenge is on Eric Roberts mind when a friend of his is killed in the ring, after fallen foul of a syndicate organising no rule and no limit illegal fights. To get to the evil promoters he must infiltrate the circuit himself. Similar to the first but with thumpingly good action scenes.");
  			pm.makePersistent(film);
  			film = new Film("BEST OF THE BEST 3: NO TURNING BACK",1996,"PHILLIP RHEE",56,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Rather a departure from the original concept, with Tommy Lee (actor and director Phillip Rhee getting involved with a small rural community which is being threatened by a gang of heavily armed thugs. Teaming up with the sheriff and a determined teacher, hes out for a confrontation. Gina Gershon went on to Showgirls and Bound.");
  			pm.makePersistent(film);
  			film = new Film("BETRAYED BY LOVE",1993,"JOHN POWER",46,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A true story, based on events which happened in Kentucky in the mid 80s. When a married woman becomes an informant for the FBI, providing them with information about an imminent bank raid, she falls for the agent in charge. When he ends the affair, much to her distress, she then vanishes, only to be found murdered days later. Is it the work of the criminals she informed on, or the FBI man.....");
  			pm.makePersistent(film);
  			film = new Film("BEVERLY HILLS COP",1984,"MARTIN BREST",185,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Eddie Murphy wisecracks his way through this comedy  thriller which occasionally startles with explicit violence. Hes a Chicago cop who goes to L.A. after his best friend is murdered there. In typical fish-out-of-water style he makes enemies with both the cops and the bad guys along the way. More jokes were added to the original script when Murphy was cast, after both Mickey Rourke and Sylvester Stallone turned the role down.");
  			pm.makePersistent(film);
  			film = new Film("BEVERLY HILLS COP II",1987,"TONY SCOTT",108,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Another outing for Axel Foley, back where he doesnt belong, called back to the West Coast on the trail of international arms smugglers led by Jurgen Prochnow and Brigitte Nielsen.The usual mixture of profanity, comedy, Murphy mugging and action set-pieces. Cops Reinhold, John Ashton and Ronny Cox return for another tour of duty.");
  			pm.makePersistent(film);
  			film = new Film("BEVERLY HILLS COP III",1993,"JOHN LANDIS",102,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Eddie Murphy steps into Axel Foleys shoes for the third time in a comic thriller, trying to crack a major forgery ring operating out of a seemingly innocent theme park in L.A. A  mix of stunts and gags, with Bronson Pinchot reprising his role as the outrageous Serge, this time flogging a nice line in designer machine guns!");
  			pm.makePersistent(film);
  			film = new Film("BEVERLY HILLS NINJA",1997,"DENNIS DUGAN",145,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The last film from Chris Farley, star of Tommy Boy and Black Sheep, before his untimely death. Here he plays a naive and innocent Ninja, having been raised by the Japanese masters of martial arts when his cradle was washed up after a shipwreck. Embarking on a quest in the US, he is secretly aided by Robin Shou (Mortal Kombat), since in terms of fighting skills and the Ninja arts, Farleys useless! Very inventive comedy.");
  			pm.makePersistent(film);
  			film = new Film("BEYOND BEDLAM",1993,"VADIM JEAN",62,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Thoroughly confused horror pic with Craig Fairbrass trying his best as a cop shattered by the death of his wife (a whining Anita Dobson) at the hands of serial killer Keith Allen. Now undergoing a radical treatment, Allen somehow now has to power to kill by telekinesis....we think. The surreal feel the film is striving for soon just disintegrates into confusing mayhem. Londons Burning star Fairbrass went onto star in Proteus.");
  			pm.makePersistent(film);
  			film = new Film("BEYOND FORGIVENESS",1994,"BOB MISIOROWSKI",156,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Rising martial arts star Thomas Ian Griffith is a tough Chicago cop whose quest for personal revenge takes him to Poland in this competent thriller. Following the trail of his brothers killers he finds himself taking on a particularly cruel branch of the Russian Mafia whose speciality is a black market in human organs for transplants. Hauer is the evil Dr. Lem, the crazed surgeon at the centre of the mystery.");
  			pm.makePersistent(film);
  			film = new Film("BIG",1988,"PENNY MARSHALL",71,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A fine performance from Tom Hanks is the highlight of this clever comedy. A young boy wants to be grown up and makes his wish at an enchanted fairground wishing machine. The next morning hes grown into the body of 30 year old Hanks, but still has the mind of a kid. Because of his understanding of the way children think hes soon employed as a consultant for a toy company, but being big also has disadvantages.");
  			pm.makePersistent(film);
  			film = new Film("BIG BULLY",1996,"STEVE MINER",170,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Disappointing comedy with Tom Arnold (True Lies) and Rick Moranis (Little Shop Of Horrors). Moranis plays a successful and confident author, returning to his home town with his family. But his joy at returning turns to horror when he meets his sons school master, who turns out to be Fang (Tom Arnold), the bully who terrorised him at school. Soon hes finding that the clock is turning back and Fangs reverting to his old ways.");
  			pm.makePersistent(film);
  			film = new Film("BIKINI CARWASH COMPANY",1991,"ED HANSON",116,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A bunch of well-endowed young ladies have an idea to raise some money by taking over a struggling carwash and having the staff work in micro-bikinis, as the title might inform you. If the idea of girls in scanty thongs being covered in suds is your thing this is for you. If not, run the other way, fast....");
  			pm.makePersistent(film);
  			film = new Film("BILL AND TEDS BOGUS JOURNEY",1991,"PETER HEWITT",190,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The Valley Dudes accidentally get themselves tangled up in Hell itself, and have to beat Death in a contest if they are to be released. Given the choice of challenge, they choose Cluedo, Battleships and Twister! Let the games commence!");
  			pm.makePersistent(film);
  			film = new Film("BILL AND TEDS EXCELLENT ADVENTURE",1989,"STEPHEN HEREK",81,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Very daft and very entertaining comedy in which the title duo, a couple of teen Valley dudes about to flunk their history course. They take charge of a time-travelling phone box and hijack all the characters from history they need, e.g. Napoleon, Abraham Lincoln and Genghis Khan. An odd concept but it works.");
  			pm.makePersistent(film);
  			film = new Film("BILLY BATHGATE",1991,"ROBERT BENTON",117,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Taken from the acclaimed bestseller by E.L.Doctorow, the fall from power of notorious gangster Dutch Schultz , told from the point of view of a young boy (Steven Hill) the newest recruit to his crime empire. Cast includes Nicole Kidman, Steve Buscemi and Stanley Tucci.");
  			pm.makePersistent(film);
  			film = new Film("BINGO!",1991,"MATTHEW ROBBINS",143,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Amiable and daft family comedy with  the title character being a pooch in a circus who becomes friends with a boy with behavioural problems. When the boys family move to the other coast, Bingo decides hes going as well!  Features TV faces David Rasche (Sledgehammer) and Cindy Williams (Laverne And Shirley),");
  			pm.makePersistent(film);
  			film = new Film("BIO-DOME",1995,"JASON BLOOM",161,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Lame comedy with Shore and Baldwin as complete numskulls who manage to get roped into a scientific experiment in which scientists and researchers are kept in a sealed  environment to see how they interact with each other. Kylie Minogue somehow got herself into this tripe.");
  			pm.makePersistent(film);
  			film = new Film("BIRD OF PREY",1995,"TEMISTOCLES LOPEZ",176,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","About to be released from prison, a young man (Von Dohlen) meets a fellow inmate with plans to kill the same man as he upon release. Things are complicated when once free he falls in love with the daughter of his intended victim, knowing that there will soon be another killer on the loose. With Richard Chamberlain (Shogun), Robert Carradine (Number One With A Bullet) and Lesley Ann Warren ( Cop).");
  			pm.makePersistent(film);
  			film = new Film("BLACK BEAUTY",1994,"CAROLINE THOMPSON",199,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Dramatic and beautifully shot adventure, based on the childrens classic by Anna Sewell. Writer and director Caroline Thompson has much of the narrative told by the beautiful black horse itself as it passes from owners both cruel and loving, finally finding contentment with the family of a country doctor. With Peter Davidson (All Creatures Great And Small), Alun Armstrong (The Saint) and Eleanor Bron.");
  			pm.makePersistent(film);
  			film = new Film("BLACK EAGLE",1986,"ERIC KARLSON",106,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Van Damme is one of the bad guys in this spy yarn shot on the island of Malta. After a US Air Force plane carrying the latest in secret navigation equipment crashes off the coast, Sho Kosugi (Pray For Death) goes undercover to salvage it. The Russians are already on the island, with Van Damme as their relentless enforcer. Good action sequences including a rooftop face-off between Kosugi and Van Damme.");
  			pm.makePersistent(film);
  			film = new Film("BLACK MASK",1996,"DAMIEN LEE",53,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Fantastic martial arts action with Jet Li as the hero of the title. Once a member of the 701 commando squad, he was one of a team of super soldiers whose nerve endings had been detached, leaving them unable to feel pain. Escaping the unit he wants a quiet life but discovers that renegade members of the 701 are trying to take over the Hong Kong drugs trade. Terrific action and non-stop pace.");
  			pm.makePersistent(film);
  			film = new Film("BLACK RAIN",1989,"RIDLEY SCOTT",66,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Stylish and brilliantly photographed thriller, with Douglas and Andy Garcia as American cops sent to Japan to return a wanted criminal. When he gives them the slip they are determined to stay on and make up for their mistake, with minimal help from the Japanese Police who regard them as barbarians. With Kate Capshaw and Yusaku Masyuda. The strong soundtrack features Living On The Edge Of The Night by Iggy Pop.");
  			pm.makePersistent(film);
  			film = new Film("BLACK ROBE",1991,"BRUCE BERESFORD",133,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Based on the true story of a young Jesuit priest at the turn of the century, sent in a missionary quest to convert North American Indians to Christianity, despite the warnings about what had happened to other that tried that task in the past. Taken from the novel by Brian Moore and starring Lothaire Bluteau from Jesus Of Montreal and La Confessional.");
  			pm.makePersistent(film);
  			film = new Film("BLAME IT ON THE BELLBOY",1991,"MARK HERMAN",108,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Entertaining enough comedy  with a dim bellboy  (Pinchot) getting utterly confused when three similarly-named men - a banker, a hit-man and a businessman - all book into a Venetian hotel on the same day, leading to a string of mix-ups. Game performances from the cast including Bryan Brown, Penelope Wilton, Richard Griffiths and Alison Steadman. At least they got a nice holiday out of it.");
  			pm.makePersistent(film);
  			film = new Film("BLANK CHEQUE",1993,"RUPERT WAINWRIGHT",100,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A young boy finds a blank cheque in the streets and fills it in for a million dollars in cash, going on an immediate lavish spending spree with his friends, but finds that there are some things money cannot buy. Mild comedy with a moral message.");
  			pm.makePersistent(film);
  			film = new Film("BLAST",1996,"ALBERT PYUN",136,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The Atlanta Olympics are the setting for this action story revolving around a terrorist incident happening in the middle of the events. After the heavily-armed gang take a bunch of swimmers hostage and make their demands, one of the people trapped in the building with them is a retired ex-martial arts champion (Linden Ashby from Mortal Kombat). Guided by crippled anti-terrorist expert Rutger Hauer, he has to free the hapless hostages.");
  			pm.makePersistent(film);
  			film = new Film("BLIND FURY",1990,"PHILLIP NOYCE",181,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Action with some sly shafts of comedy, based on the Japanese character of Zatiochi, a blind Samurai. Hauer plays a Vietnam veteran blinded by a landmine, who is taught Zen and the art of swordsmanship by a Shaolin master. Travelling back to America he soon gets involved with the Mafia and a kidnapped child. Good tongue-in-cheek stuff, with a cameo from Sho Kosugi (Pray For Death) as Hauers final opponent.");
  			pm.makePersistent(film);
  			film = new Film("BLINDFOLD: ACTS OF OBSESSION",1994,"LAWRENCE SIMEONE",136,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Shannen Doherty from Beverly Hills 90210 is the lead in this story of sexual obsession. Shes bored after two years of marriage so, with her husbands encouragement, goes to a sex therapist (Nelson). He advises her to act out her fantasies, which she eagerly does. but after every encounter the police discover the victim of a serial killer. The bodies have all been blindfolded, much in the manner of Dohertys fetish.");
  			pm.makePersistent(film);
  			film = new Film("BLINDSIDE",1992,"RUTGER HAUER, REBECCA DE MORNAY",97,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Tense thriller in witch a  holidaying couple get  involved in a hit and run accident in Mexico. They  leave the scene and their victim on the road. Once back in the States they believe theyve got away with their crime, until a man arrives on the doorstep and hints he knows what they did. Is his motive blackmail, or something even more sinister?  From the director of Freejack and Under Siege 2.");
  			pm.makePersistent(film);
  			film = new Film("BLINK",1993,"MICHAEL APTED",197,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The old blind girl in peril scenario again with Madeline Stowe as the afflicted victim. Having undergone surgery to restore her sight to a mosaic of shadows and shapes she witnesses and murder and the killer thinks shell be able to recognise him. Aidan Quinn is the cop assigned to protect her and James Remar carries off his familiar menacing role with ease.");
  			pm.makePersistent(film);
  			film = new Film("BLOOD AND WINE",1997,"BOB RAFELSON",172,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Strong and involving drama reuniting Nicholson and director Rafelson from Five Easy Pieces. Nicholson is a small-time hood who has stolen a valuable necklace. After his wife (Judy Davis) finally separates from him, taking their son, she accidentally takes the jewellery, causing various unpleasant characters to get on her trail. Caine gives a great performance as a wheezing, dying petty crook.");
  			pm.makePersistent(film);
  			film = new Film("BLOOD IN BLOOD OUT",1993,"TAYLOR HACKFORD",70,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","A three-hour sprawl following three Chicano friends raised in the ethnic suburb of east L.A. Watching them go through 20 years their paths are constantly intertwined with tension and occasional violence. From the director of Against All Odds.");
  			pm.makePersistent(film);
  			film = new Film("BLOOD SIMPLE",1983,"JOEL & ETHAN COEN",116,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Complex and dark thriller from the Coen Brothers, makers of Fargo and The Hudsucker Proxy. A jealous husband (Dan Hedaya) wants to kill his adulterous wife and her lover (McDormand and Getz). Hiring a sleazy private eye (M.Emmet Walsh) to do the deed, the gumshoe fakes the death of the couple but this is only the start of a web of confusion, betrayals and murder. Gripping and labyrinthine.");
  			pm.makePersistent(film);
  			film = new Film("BLOODFIST 3: FORCED TO FIGHT",1991,"OLLY SASSONE",169,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Don The Dragon Wilson is banged up for a crime he didnt commit in this average martial-arts story. He is drawn into a series of illegal fighting bouts, each one more brutal than the last. The only way to survive is to defeat your opponent. With Richard Roundtree from Shaft and undefeated karate champion Joe Lewis.");
  			pm.makePersistent(film);
  			film = new Film("BLOODSPORT",1987,"NEWT ARNOLD",135,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","One of Van Dammes first major roles in an entertaining smack-em-up supposedly based on a true story, and you can believe that if you like. He plays Frank Dux , a competitor in a secret martial arts contest, the Kumite, the winner being the last man standing. Virtually non-stop martial arts after the first half hour.  The Crying Games Forest Whitaker has a part in this, although he doesnt talk about it.");
  			pm.makePersistent(film);
  			film = new Film("BLOWN AWAY",1993,"STEPHEN HOPKINS",130,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Tommy Lee Jones is the IRA bomber with a grudge and Jeff Bridges is the Boston Bomb Squad officer  with a deadly link to the terrorist in this explosive thriller. Escaping from jail, Jones travels to the States and torments Bridges and his men with booby traps and tricks, before turning his attention to Bridges family.");
  			pm.makePersistent(film);
  			film = new Film("BLUE CHIPS",1994,"WILLIAM FRIEDKIN",43,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Basketball drama marking the film debut of sports superstar Shaquille ONeal, later to be seen in Steel. Nolte plays a basketball coach with an impeccable reputation, but now finds himself facing a losing season. His only recourse is to pay bribes in order to secure the new seasons best players. Basketball fans will like the on-court action, but many will think Shaq should stick to the hoop game.");
  			pm.makePersistent(film);
  			film = new Film("BLUE ICE",1992,"RUSSELL MULCAHY",105,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","The title is the name given to the frozen deposits which fall from aircraft toilet outlet pipes. Whats that to do with this spy yarn is anyones guess. Michael Caine stars as a retired agent who gets involved with ambassadors wife Sean Young, then is caught up in a series of political murders.  But theres good British support in the cast from Ian Holm, Bob Hoskins, Alun Armstrong and Jack Shepard.");
  			pm.makePersistent(film);
  			film = new Film("BLUE JUICE",1995,"PETER SALMI",195,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Sean Pertwee is an obsessive surfer on the decidedly unsunny  Cornish coast who finally has time called by his long-standing girlfriend (Catherine Zeta Jones). Its either surfing or her. While his mates try to persuade him to stick to the waves, the thought of her leaving threatens to become too much. An early role for Ewan McGregor as one of Pertwees friends, and small parts for Keith Allen, Jenny Agutter and Mark Frost.");
  			pm.makePersistent(film);
  			film = new Film("BLUE TIGER",1994,"NORBERTO BARBA",140,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Excellent, intelligent thriller from the makers of American Yakuza. Virginia Madsen (Candyman) plays a young mother whose child is killed when caught in a gun battle between rival gangs. Recovering from a breakdown she vows to kill the man who pulled the trigger, a member of the Yakuza , and infiltrates that secret society. With Harry Dean Stanton as the dying tattooist who tries to dissuade her from her mission.");
  			pm.makePersistent(film);
  			film = new Film("BLUE VELVET",1986,"DAVID LYNCH",76,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","David Lynchs haunting and alarming tale of obsession and madness, with clean-cut MacLachlan being drawn into a sinister world after discovering a severed ear in a garden. A small American town turns out to be a bed of psychosis involving a kidnapped nightclub singer and the distinctly disturbed Frank (a chilling performance from Dennis Hopper). Features Isabella Rossellini, Dean Stockwell and Laura Dern.");
  			pm.makePersistent(film);
  			film = new Film("BOB ROBERTS",1992,"TIM ROBBINS",81,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Very sharp political satire, directed by and starring Tim Robbins (The Player). He plays the title character, a right-wing politician running for office and trying to appeal to youth with his use of music and videos. Alan Rickman is terrific as his religious maniac of an adviser. With cameo appearances from real political figures as well as actors such as James Spader and David Strathairn.");
  			pm.makePersistent(film);
  			film = new Film("BODY MELT",1993,"PHILIP BROPHY",136,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat.","Failed attempt at black comedy in which a scientist tests his experimental drug on the inhabitants of a small rural town. But it has a few unpleasant side-effects - the recipients start melting away or  their organs explode. Stars a few familiar Aussie soap opera  faces, before they start running down their shirts.");
  			pm.makePersistent(film);
  		} finally {
			pm.close();
		}
    }
   
}
